### PR TITLE
Qualify Argo.Decodable for Swift 3.2

### PR DESCRIPTION
**Pull request by dcaunt**
Fixes compilation with Swift 3.2.

### CODE REVIEW

**Comment by mdiep** [comment]
Weird. Any idea why this is required?

**Review by mdiep — APPROVED** [review]

**Comment by dcaunt** [comment]
It appears to be due to the addition of  [`Decodable`](https://developer.apple.com/documentation/swift/decodable) via [SE-0166](https://github.com/apple/swift-evolution/blob/master/proposals/0166-swift-archival-serialization.md), see also https://github.com/ikesyo/Himotoki/pull/183.

**Comment by mdiep** [comment]
Oh, right! That makes sense.

Thanks for fixing this!

**Comment by ikesyo** [comment]
Cutting a new release with this and #85 will be good for smooth Xcode 9 migration. See also https://github.com/Carthage/Carthage/pull/2064. 🙏

**Pull request merged**
