### PR TITLE
Migrate to Swift 5.2

### PR DESCRIPTION
**Pull request by olejnjak**
- migrate to Swift 5.2
- update ReactiveSwift
- remove non-native Result dependency

### CODE REVIEW

**Comment by eliperkins** [comment]
Rockin', @olejnjak! Thanks for getting this started! I updated the PR to fix the Xcode-based builds.

Additionally, I removed `ResultExtensions.swift` in https://github.com/mdiep/Tentacle/pull/109/commits/77a61b5cba08dd7bfdebffcc7b559d56aa57d1e1, since this isn't needed for this project specifically. The direct access to `result.value` from the old Result framework can be replaced by a `try result.get()`, and the explicit Equatable conformance within this project is already implemented in the new Result type.

Take a look and let me know what you think! I'll land this and release a new major version if we're happy with where this landed.

**Review by eliperkins — APPROVED** [review]
I touched up the PR, getting this ready for CI and such.

Let me know whatcha think @olejnjak

**Comment by olejnjak** [comment]
Great 🙂❤️

**Comment by eliperkins** [comment]
Released! https://github.com/mdiep/Tentacle/releases/tag/0.14.0

**Pull request merged**
