### PR TITLE
Fix Swift 2.3 optional string interpolation bug

### PR DESCRIPTION
**Pull request by jasonboyle**

### CODE REVIEW

**Comment by Palleas** [comment]
Thanks! 😄

**Review by mdiep — APPROVED** [review]
Awesome! Thanks for including a test. ✨

**Comment by ikesyo** [comment]
Nice catch! I'd love to get a patch release including this for https://github.com/Carthage/Carthage/issues/1505.

**Comment by mdiep** [comment]
I'll do that later tonight or in the morning. 👍🏻

**Comment by mdiep** [comment]
https://github.com/mdiep/Tentacle/releases/tag/0.4.1

**Pull request merged**
